version: "3.6"

services:
  db:
    image: mysql:8.0.28
    container_name: "typeorm-mysql"
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "EnglishCenter"