"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const guard_1 = require("../../middlewares/guard");
const role_constant_1 = require("../../utils/constants/role.constant");
const signin_1 = require("./signin");
const signup_1 = require("./signup");
const router = express.Router();
router.use((0, guard_1.guard)([role_constant_1.UserRole.GUEST]), signin_1.SigninRouter);
router.use((0, guard_1.guard)([role_constant_1.UserRole.GUEST, role_constant_1.UserRole.ADMIN, role_constant_1.UserRole.EMPLOYEE]), signup_1.SignupRouter);
exports.default = router;
